# Generated by Django 2.1.5 on 2019-10-24 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=140, validators=[django.core.validators.RegexValidator(message='Enter only letters or numbers for address', regex='^[a-zA-Z0-9 ,.-]+$')])),
                ('address2', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(default='', max_length=140)),
                ('state', models.CharField(default='', max_length=2)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=13, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=13, null=True)),
                ('displayed', models.BooleanField(default=False, editable=False)),
                ('submitter', models.CharField(default='', max_length=140)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('organization', models.CharField(blank=True, default='', max_length=50)),
                ('occupation', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
