# Generated by Django 2.1.5 on 2019-09-28 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=140, validators=[django.core.validators.RegexValidator(message='Enter only letters or numbers for address', regex='^[a-zA-Z0-9 ,.-]+$')]),
        ),
    ]
