# Generated by Django 2.1.5 on 2019-10-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190928_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
