# Generated by Django 2.1.5 on 2019-07-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190718_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='user',
        ),
    ]
