# Generated by Django 2.1.5 on 2019-07-08 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190609_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=140, validators=[django.core.validators.RegexValidator(message='Enter only letters or numbers for address', regex='^[a-zA-Z0-9 .-]+$')]),
        ),
    ]
